### ISSUE TITLE
indexmap support?

### ISSUE THREAD

**Issue by SamuelMarks** [fizyr/subst#24]
Would be great to have. Currently get this error:
> |
> |                 subst::substitute(input_as_utf8, &env.into());
> |                 ^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `M` declared on the function `substitute`
> |
>  = note: cannot satisfy `<_ as VariableMap<'_>>::Value == _`
help: consider specifying the generic argument
> |
> |                 subst::substitute::<M>(input_as_utf8, &env.into());
> |                                  +++++

Where `env` is `indexmap::IndexMap<String, String>`.

Obviously I can just do the non ergonomic:
```rs
let mut hm = std::collections::HashMap::<String, String>::with_capacity(env.len());
for (k,v) in env.iter() {
    hm.insert(k.to_owned(), v.to_owned());
}
```

**Comment by de-vri-es** [comment]
I agree, `indexmap` support makes sense! PR #25 opened to implement it (behind a feature flag).

**Comment by SamuelMarks** [comment]
Thanks
